stages:
- Install dependencies
- Code Quality

variables:
  # Needed for NPM Cache
  npm_config_cache: "$CI_PROJECT_DIR/.npm"

########################################################################
#  BEGIN CACHE                                                         #
########################################################################

.NPM Cache: &npm_cache
  key: npm-cache
  paths:
    - .npm
    - node_modules
  policy: pull-push

.Composer Cache: &composer_cache
  key: composer-cache
  paths:
    - composer.phar
    - vendor
    - web/wp
    - web/wp-content/mu-plugins/wp-mu-cleanup
     <%_ if (wpRocket) { _%>
    - web/wp-content/plugins/wp-rocket
    <%_ } _%>
    <%_ if (wordfence) { _%>
    - web/wp-content/plugins/wordfence
    <%_ } _%>
    <%_ if (classicEditor) { _%>
    - web/wp-content/plugins/classic-editor
    <%_ } _%>
    <%_ if (yoastSeo) { _%>
    - web/wp-content/plugins/wordpress-seo
    <%_ } _%>
    <%_ if (acf) { _%>
    - web/wp-content/plugins/advanced-custom-fields-pro
    <%_ } _%>
  policy: pull-push

########################################################################
#  END CACHE                                                           #
########################################################################

########################################################################
#  BEGIN INSTALL                                                       #
########################################################################

NPM Install:
  stage: Install dependencies
  image: node:12
  cache:
    <<: *npm_cache
  only:
    refs:
      - merge_requests
    changes:
      - package.json
      - package-lock.json
      - .gitlab-ci.yml
  script:
    - npm ci

Composer Install:
  stage: Install dependencies
  image: php:7.0
  cache:
    <<: *composer_cache
  only:
    refs:
      - merge_requests
    changes:
      - composer.json
      - composer.lock
      - .gitlab-ci.yml
  script:
    - apt-get update
    - apt-get install -y unzip wget zip
    - wget https://raw.githubusercontent.com/composer/getcomposer.org/6e874537c7ff87f03f99dc8dea1f2c48e4274da3/web/installer -O - -q | php -- --quiet
    - php composer.phar install --prefer-dist --no-progress --no-suggest

########################################################################
#  END INSTALL                                                         #
########################################################################

########################################################################
#  BEGIN CODE QUALITY                                                  #
########################################################################

PHPCS:
  stage: Code Quality
  image: php:7.0
  cache:
    <<: *composer_cache
    policy: pull
  only:
    refs:
      - merge_requests
    changes:
      - composer.json
      - composer.lock
      - .gitlab-ci.yml
      - "**/*.php"
  before_script:
    - apt-get update
    - apt-get install -y git unzip zip
    - php composer.phar install --prefer-dist --no-progress --no-suggest
  script:
    - php composer.phar run lint

ESLint:
  stage: Code Quality
  image: node:12
  cache:
    <<: *npm_cache
    policy: pull
  only:
    refs:
      - merge_requests
    changes:
      - package.json
      - package-lock.json
      - .gitlab-ci.yml
      - "wep/wp-content/themes/lumapps/src/js/**/*.js"
      - "wep/wp-content/themes/lumapps/src/js/**/*.vue"
  before_script:
    - npm ci
  script:
    - npm run lint:scripts

Stylelint:
  stage: Code Quality
  image: node:12
  cache:
    <<: *npm_cache
    policy: pull
  only:
    refs:
      - merge_requests
    changes:
      - package.json
      - package-lock.json
      - .gitlab-ci.yml
      - "wep/wp-content/themes/lumapps/src/js/**/*.vue"
      - "wep/wp-content/themes/lumapps/src/css/**/*.scss"
  before_script:
    - npm ci
  script:
    - npm run lint:styles


########################################################################
#  END CODE QUALITY                                                    #
########################################################################
